/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-06 at 15:53:59 UTC 
 * Modify at your own risk.
 */

package com.darkart.foodmap.server.foodendpoint;

/**
 * Service definition for Foodendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link FoodendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Foodendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the foodendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "foodendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Foodendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Foodendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getFood".
   *
   * This request holds the parameters needed by the the foodendpoint server.  After setting any
   * optional parameters, call the {@link GetFood#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetFood getFood(java.lang.String id) throws java.io.IOException {
    GetFood result = new GetFood(id);
    initialize(result);
    return result;
  }

  public class GetFood extends FoodendpointRequest<com.darkart.foodmap.server.foodendpoint.model.Food> {

    private static final String REST_PATH = "food/{id}";

    /**
     * Create a request for the method "getFood".
     *
     * This request holds the parameters needed by the the foodendpoint server.  After setting any
     * optional parameters, call the {@link GetFood#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetFood#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetFood(java.lang.String id) {
      super(Foodendpoint.this, "GET", REST_PATH, null, com.darkart.foodmap.server.foodendpoint.model.Food.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetFood setAlt(java.lang.String alt) {
      return (GetFood) super.setAlt(alt);
    }

    @Override
    public GetFood setFields(java.lang.String fields) {
      return (GetFood) super.setFields(fields);
    }

    @Override
    public GetFood setKey(java.lang.String key) {
      return (GetFood) super.setKey(key);
    }

    @Override
    public GetFood setOauthToken(java.lang.String oauthToken) {
      return (GetFood) super.setOauthToken(oauthToken);
    }

    @Override
    public GetFood setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetFood) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetFood setQuotaUser(java.lang.String quotaUser) {
      return (GetFood) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetFood setUserIp(java.lang.String userIp) {
      return (GetFood) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetFood setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetFood set(String parameterName, Object value) {
      return (GetFood) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertFood".
   *
   * This request holds the parameters needed by the the foodendpoint server.  After setting any
   * optional parameters, call the {@link InsertFood#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.darkart.foodmap.server.foodendpoint.model.Food}
   * @return the request
   */
  public InsertFood insertFood(com.darkart.foodmap.server.foodendpoint.model.Food content) throws java.io.IOException {
    InsertFood result = new InsertFood(content);
    initialize(result);
    return result;
  }

  public class InsertFood extends FoodendpointRequest<com.darkart.foodmap.server.foodendpoint.model.Food> {

    private static final String REST_PATH = "food";

    /**
     * Create a request for the method "insertFood".
     *
     * This request holds the parameters needed by the the foodendpoint server.  After setting any
     * optional parameters, call the {@link InsertFood#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertFood#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.darkart.foodmap.server.foodendpoint.model.Food}
     * @since 1.13
     */
    protected InsertFood(com.darkart.foodmap.server.foodendpoint.model.Food content) {
      super(Foodendpoint.this, "POST", REST_PATH, content, com.darkart.foodmap.server.foodendpoint.model.Food.class);
    }

    @Override
    public InsertFood setAlt(java.lang.String alt) {
      return (InsertFood) super.setAlt(alt);
    }

    @Override
    public InsertFood setFields(java.lang.String fields) {
      return (InsertFood) super.setFields(fields);
    }

    @Override
    public InsertFood setKey(java.lang.String key) {
      return (InsertFood) super.setKey(key);
    }

    @Override
    public InsertFood setOauthToken(java.lang.String oauthToken) {
      return (InsertFood) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertFood setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertFood) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertFood setQuotaUser(java.lang.String quotaUser) {
      return (InsertFood) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertFood setUserIp(java.lang.String userIp) {
      return (InsertFood) super.setUserIp(userIp);
    }

    @Override
    public InsertFood set(String parameterName, Object value) {
      return (InsertFood) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listFood".
   *
   * This request holds the parameters needed by the the foodendpoint server.  After setting any
   * optional parameters, call the {@link ListFood#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListFood listFood() throws java.io.IOException {
    ListFood result = new ListFood();
    initialize(result);
    return result;
  }

  public class ListFood extends FoodendpointRequest<com.darkart.foodmap.server.foodendpoint.model.CollectionResponseFood> {

    private static final String REST_PATH = "food";

    /**
     * Create a request for the method "listFood".
     *
     * This request holds the parameters needed by the the foodendpoint server.  After setting any
     * optional parameters, call the {@link ListFood#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListFood#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListFood() {
      super(Foodendpoint.this, "GET", REST_PATH, null, com.darkart.foodmap.server.foodendpoint.model.CollectionResponseFood.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListFood setAlt(java.lang.String alt) {
      return (ListFood) super.setAlt(alt);
    }

    @Override
    public ListFood setFields(java.lang.String fields) {
      return (ListFood) super.setFields(fields);
    }

    @Override
    public ListFood setKey(java.lang.String key) {
      return (ListFood) super.setKey(key);
    }

    @Override
    public ListFood setOauthToken(java.lang.String oauthToken) {
      return (ListFood) super.setOauthToken(oauthToken);
    }

    @Override
    public ListFood setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListFood) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListFood setQuotaUser(java.lang.String quotaUser) {
      return (ListFood) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListFood setUserIp(java.lang.String userIp) {
      return (ListFood) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListFood setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListFood setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListFood set(String parameterName, Object value) {
      return (ListFood) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeFood".
   *
   * This request holds the parameters needed by the the foodendpoint server.  After setting any
   * optional parameters, call the {@link RemoveFood#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveFood removeFood(java.lang.String id) throws java.io.IOException {
    RemoveFood result = new RemoveFood(id);
    initialize(result);
    return result;
  }

  public class RemoveFood extends FoodendpointRequest<Void> {

    private static final String REST_PATH = "food/{id}";

    /**
     * Create a request for the method "removeFood".
     *
     * This request holds the parameters needed by the the foodendpoint server.  After setting any
     * optional parameters, call the {@link RemoveFood#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveFood#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveFood(java.lang.String id) {
      super(Foodendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveFood setAlt(java.lang.String alt) {
      return (RemoveFood) super.setAlt(alt);
    }

    @Override
    public RemoveFood setFields(java.lang.String fields) {
      return (RemoveFood) super.setFields(fields);
    }

    @Override
    public RemoveFood setKey(java.lang.String key) {
      return (RemoveFood) super.setKey(key);
    }

    @Override
    public RemoveFood setOauthToken(java.lang.String oauthToken) {
      return (RemoveFood) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveFood setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveFood) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveFood setQuotaUser(java.lang.String quotaUser) {
      return (RemoveFood) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveFood setUserIp(java.lang.String userIp) {
      return (RemoveFood) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveFood setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveFood set(String parameterName, Object value) {
      return (RemoveFood) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateFood".
   *
   * This request holds the parameters needed by the the foodendpoint server.  After setting any
   * optional parameters, call the {@link UpdateFood#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.darkart.foodmap.server.foodendpoint.model.Food}
   * @return the request
   */
  public UpdateFood updateFood(com.darkart.foodmap.server.foodendpoint.model.Food content) throws java.io.IOException {
    UpdateFood result = new UpdateFood(content);
    initialize(result);
    return result;
  }

  public class UpdateFood extends FoodendpointRequest<com.darkart.foodmap.server.foodendpoint.model.Food> {

    private static final String REST_PATH = "food";

    /**
     * Create a request for the method "updateFood".
     *
     * This request holds the parameters needed by the the foodendpoint server.  After setting any
     * optional parameters, call the {@link UpdateFood#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateFood#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.darkart.foodmap.server.foodendpoint.model.Food}
     * @since 1.13
     */
    protected UpdateFood(com.darkart.foodmap.server.foodendpoint.model.Food content) {
      super(Foodendpoint.this, "PUT", REST_PATH, content, com.darkart.foodmap.server.foodendpoint.model.Food.class);
    }

    @Override
    public UpdateFood setAlt(java.lang.String alt) {
      return (UpdateFood) super.setAlt(alt);
    }

    @Override
    public UpdateFood setFields(java.lang.String fields) {
      return (UpdateFood) super.setFields(fields);
    }

    @Override
    public UpdateFood setKey(java.lang.String key) {
      return (UpdateFood) super.setKey(key);
    }

    @Override
    public UpdateFood setOauthToken(java.lang.String oauthToken) {
      return (UpdateFood) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateFood setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateFood) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateFood setQuotaUser(java.lang.String quotaUser) {
      return (UpdateFood) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateFood setUserIp(java.lang.String userIp) {
      return (UpdateFood) super.setUserIp(userIp);
    }

    @Override
    public UpdateFood set(String parameterName, Object value) {
      return (UpdateFood) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Foodendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Foodendpoint}. */
    @Override
    public Foodendpoint build() {
      return new Foodendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link FoodendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setFoodendpointRequestInitializer(
        FoodendpointRequestInitializer foodendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(foodendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
